/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VprocessJNI */

#ifndef _Included_VprocessJNI
#define _Included_VprocessJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VprocessJNI
 * Method:    create_obj
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_VprocessJNI_create_1obj
  (JNIEnv *env, jobject obj, jint size, jint fs, jint fsize, jint fmove);

/*
 * Class:     VprocessJNI
 * Method:    process_feat
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_VprocessJNI_process_1feat
  (JNIEnv *env, jobject obj, jlong p_tm, jdoubleArray data);

/*
 * Class:     VprocessJNI
 * Method:    compare
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_VprocessJNI_compare
  (JNIEnv *env, jobject obj, jlong p1, jlong p2);

/*
 * Class:     VprocessJNI
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_VprocessJNI_destroy
  (JNIEnv *env, jobject obj, jlong p_tm);

#ifdef __cplusplus
}
#endif
#endif
